site_name: sai
site_url: "https://xin-huang.github.io/sai"
repo_url: "https://github.com/xin-huang/sai"
edit_uri: ""
docs_dir: 'docs'
theme:
  name: material
  palette:
    primary: teal
    accent: indigo
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
- Home: 'index.md'
- User Guide:
  - Calculate Statistics: 'userguide/score.md'
  - Extract Outliers: 'userguide/outlier.md'
